config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/about'

  devise_for :users
  resources :users
    resources :users do
        resources :areas
        resources :educations
        resources :researches
        resources :courses
    end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: "pages#home"
end

app/models/research.rb
class Research < ApplicationRecord
    belongs_to :user
end

app/controllers/researches_controller.rb
class ResearchesController < ApplicationController
  before_action :set_research, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
    
  # GET /researches
  # GET /researches.json
  def index
    @researches = Research.all
  end

  # GET /researches/1
  # GET /researches/1.json
  def show
  end

  # GET /researches/new
  def new
    @research = Research.new
  end

  # GET /researches/1/edit
  def edit
  end

  # POST /researches
  # POST /researches.json
  def create
    @research = Research.new(research_params)
      @research.save
      redirect_to current_user
  end

  # PATCH/PUT /researches/1
  # PATCH/PUT /researches/1.json
  def update
    respond_to do |format|
      if @research.update(research_params)
          format.html { redirect_to current_user, notice: 'Research was successfully updated.' }
        format.json { render :show, status: :ok, location: @research }
      else
        format.html { render :edit }
        format.json { render json: @research.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /researches/1
  # DELETE /researches/1.json
  def destroy
    @research.destroy
    respond_to do |format|
        format.html { redirect_to current_user, notice: 'Research was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_research
      @research = Research.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def research_params
      params.require(:research).permit(:name, :user_id)
    end
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/views/researches/_form.html.erb
<%= form_for(research) do |f| %>
  <% if research.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(research.errors.count, "error") %> prohibited this research from being saved:</h2>

      <ul>
      <% research.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/researches/edit.html.erb
<h1>Editing Research</h1>

<%= render 'form', research: @research %>

<%= link_to 'Show', @research %> |
<%= link_to 'Back', researches_path %>

app/views/researches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Researches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @researches.each do |research| %>
      <tr>
        <td><%= research.name %></td>
        <td><%= link_to 'Show', research %></td>
        <td><%= link_to 'Edit', edit_research_path(research) %></td>
        <td><%= link_to 'Destroy', research, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Research', new_research_path %>

app/views/researches/new.html.erb
<h1>New Research</h1>

<%= render 'form', research: @research %>

<%= link_to 'Back', researches_path %>

app/views/researches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @research.name %>
</p>

<%= link_to 'Edit', edit_research_path(@research) %> |
<%= link_to 'Back', researches_path %>